name: Cypress Orange_HRM
on : push

jobs:
  Cypress-setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: precommit
        run: npm ci
      - run: npm run precommit
job:
  Cypress-run:   
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run test 
          browser: chrome

      - name: Uploading Artifacts
        uses: actions/upload-artifact@v3
        if: always()    
        with:
          name: cypress-execution-report
          path: orange_hrm/reports
          retention-days: 30
